Disable symbol resolution in executable for Windows builds.
Explicitly set `resolve_symbols_in_exec` to false for Windows builds, overriding the default true value.

Otherwise you can get build errors like this when building LiteRT targets:

```
bazelisk --output_base=C:\bzl_lrtlm build --config=windows @litert//litert/vendors/intel_openvino/dispatch:LiteRtDispatch

ERROR: C:/bzl_lrtlm/external/litert/litert/c/BUILD:1003:11: Illegal ambiguous match on configurable attribute "deps" in @@litert//litert/c:litert_runtime_c_api_shared_lib:
@@litert//litert/c:resolve_symbols_in_exec
@@litert//litert:windows
Multiple matches are not allowed unless one is unambiguously more specialized or they resolve to the same value. See https://bazel.build/reference/be/functions#select.
```

This simplifies the user flow for the Intel launch, instead of asking the user to clone LiteRT-LM then look up the LiteRT reference and clone LiteRT and checkout that  reference to build the dispatch DLL, the user can simply use the `@litert` prefix from LiteRT-LM.

LiteRT-LM-PiperOrigin-RevId: 916879853